project:
  type: website
  output-dir: docs

website:
  title: "4th China Pharma R user group meeting"
  description: "The 4th official meet-up for the China Pharmaceutical Industry R User Group"
  site-url: https://github.com/pharmarug/pharmarug-2026
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: "house-fill"
      - href: program.qmd
        text: Program
        icon: "folder"
      - href: highlights.qmd
        text: Event highlights
        icon: "camera"
  page-footer:
    center:
      - text: "Past Events"
        href: https://pharmarug.github.io/index.html

format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 1.5rem
    theme: cosmo
    mainfont: system-ui
    fontcolor: "#161b58"
    css: styles.css
    toc: false

editor: source
